### PR TITLE
Account management UI

### PR DESCRIPTION
**Pull request by anasinik**
I have designed the user profile view. You can access it by clicking the corresponding icon in the bottom navigation bar. In this view, you can see basic user information. To edit the profile, simply click on the pencil icon in the top-right corner ✏️.

For the password change, I have implemented a separate dialog, and in the form below, you can modify all details except the email, as specified in the requirements.

There are also buttons for deactivating and upgrading the profile, but they are not functional yet since they require backend checks, and as you know, we don't have that set up yet ⚙️.

Please take a look when you have time and let me know if you notice any mistakes or areas for improvement 🙏.

### CODE REVIEW

**Review by lazarnagulov — COMMENTED** [review]
Everything looks fine and navigation is functional, but the edit button is purple. 🟣

**Comment by anasinik** [comment]
> Everything looks fine and navigation is functional, but the edit button is purple. 🟣

I don’t know how to change it. For some reason, the color doesn’t change no matter which attribute I use. If you know how to fix it, please go ahead. I’ve already spent some time on it, but I couldn’t figure out the way.

**Comment by lazarnagulov** [comment]
> > Everything looks fine and navigation is functional, but the edit button is purple. 🟣
> 
> I don’t know how to change it. For some reason, the color doesn’t change no matter which attribute I use. If you know how to fix it, please go ahead. I’ve already spent some time on it, but I couldn’t figure out the way.

I did it, let me know if you like it!

image0

**Comment by anasinik** [comment]
> > > Everything looks fine and navigation is functional, but the edit button is purple. 🟣
> > 
> > 
> > I don’t know how to change it. For some reason, the color doesn’t change no matter which attribute I use. If you know how to fix it, please go ahead. I’ve already spent some time on it, but I couldn’t figure out the way.
> 
> I did it, let me know if you like it! The button tag looks like this:
> 
> ```
> <Button
>       android:id="@+id/editAccountButton"
>       android:layout_width="wrap_content"
>       android:layout_height="wrap_content"
>       app:iconSize="32dp"
>       app:icon="@drawable/ic_edit"
>       app:iconTint="@color/md_theme_primary"
>       app:backgroundTint="@color/md_theme_primaryContainer"
>       android:contentDescription="Edit"
>       app:layout_constraintTop_toTopOf="parent"
>       app:layout_constraintEnd_toEndOf="parent"
>       android:layout_marginTop="16dp"
>       android:paddingStart="40dp"
>       android:onClick="navigateToEditAccount"/>
> ```
> 
> image0

Thank you so, so much!!! :))

**Review by lazarnagulov — APPROVED** [review]
Now everything looks fine!
Approved! 🚀

**Pull request merged**
